version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ogadityahota/swarajdesk-web
    container_name: swarajdesk-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${API_URL}
      - NEXT_PUBLIC_WS_URL=${WS_URL}
    restart: unless-stopped